sudo: required
services:
    - docker
    
before_install:
    - docker build -t means2014/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true means2014/react-test npm test
    
after_success:
    - docker build -t means2014/multi-client ./client
    - docker build -t means2014/multi-nginx ./nginx
    - docker build -t means2014/multi-server ./server
    - docker build -t means2014/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push means2014/multi-client
    - docker push means2014/multi-nginx
    - docker push means2014/multi-server
    - docker push means2014/multi-worker
    
deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucker_name: elasticbeanstalk-us-east-2-784652194058
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY